library(dplyr)
library(ggpubr)
library(multcomp)
library(car)
x<-read.csv("C:\\Users\\aneek\\Documents\\Upwork\\ANOVA\\ANOVA_BD.csv",header=TRUE)
x_aov <- aov(x$tip~factor(x$day))
summary(x_aov)
ggboxplot(x,x="day",y="tip",color="day",palette = c("#00AFBB", "#E7B800","#76EE00","#EE7621"))
plot(x_aov,1)
leveneTest(tip~factor(day),data=x)
plot(x_aov,2)
aov_residuals <- residuals(object = x_aov)
shapiro.test(x = aov_residuals )
