library(dplyr)
library(nlme)
library(ggpubr)
library(multcomp)
library(car)
library(ggplot2)
x<-read.csv("C:\\Users\\aneek\\Documents\\Upwork\\ANOVA\\Private\\tips_2WAY_EQ.csv",header=TRUE)
x$sex<-as.factor(x$sex)
x$smoker<-as.factor(x$smoker)
table(x$sex,x$smoker)
dev.new()
plot(x$tip)
dev.new()
ggboxplot(x, x = "sex", y = "tip", color = "smoker",palette = c("#00AFBB", "#E7B800"))
dev.new()
ggline(x, x = "sex", y = "tip", color = "smoker", add = c("mean_se", "dotplot"), palette = c("#00AFBB", "#E7B800"))
res.aov3 <- aov(tip ~ sex + smoker + sex:smoker, data = x)
summary(res.aov3)
dev.new()
plot(res.aov3,1)
leveneTest(tip ~ sex*smoker, data = x)
dev.new()
plot(res.aov3, 2)
aov_residuals <- residuals(object = res.aov3)
shapiro.test(x = aov_residuals )
